---

- name: disable and stop rpcbind service and socket if uninstalling rpcbind
  service:
    name: '{{ item }}'
    state: stopped
    enabled: no
  with_items:
    - '{{ rpcbind_service }}'
    - '{{ rpcbind_socket }}'
  when: rpcbind_package_state == 'absent'

- name: handle rpcbind packages
  package:
    name: '{{ rpcbind_packages }}'
    state: '{{ rpcbind_package_state }}'
  tags:
    - 'role::rpcbind'
    - 'role::rpcbind:install'

- name: disable and stop rpcbind
  service:
    name: '{{ rpcbind_service }}'
    state: '{{ rpcbind_state }}'
    enabled: no
  tags:
    - 'role::rpcbind'
    - 'role::rpcbind:install'
  when: not rpcbind_package_state == 'absent'
